### PR TITLE
Next web

### PR DESCRIPTION
**Pull request by mihrab34**

### CODE REVIEW

**Comment by SantiagoGuerra** [comment]
Hello @Qoosim and @mihrab34, excellent work, the effort you have put into this project is remarkable.

Here are some suggestions of mine for you to implement in your project:

* Make a more descriptive pull request, so you can show the characteristics of the branch in which you want "merge"
* You can use a general container; avoid using classes like ".container-1, .container-2, .img-in1, .img-in2"
* Resolve conflicts at merge branches
* Fix the positioning of some elements

**Comment by Usagib** [comment]
Hi @Qoosim @mihrab34 ! This project looks great!, here is my suggestion for next project building:

- Try to abstract some classes: use for example .image-size to resize all images instead of using separate classes for each element.

looks like you are only missing some element align and your project is good to go

great job and happy coding!

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi team :wave: 

Nice work so far. You guys have really put in lots of efforts. Your commit messages are good, keep it up. You should improve your PR description too.

That said, let's fix these issues below.

#### Navigation bar
Your solution doesn't behave as expected at the different breakpoints.
##### Medium version changes
- [ ] TWN logo appears at the leftmost part.

TNW-navbar-2

##### Small version changes
- [ ] Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to search icon).

TNW-navbar-3

- [ ] Page doesn't behave well. ( _Your content overlap as you tend towards the medium breakpoint_ )

tnw-overflow

tnw-overflow2

tnw-overlow3

- [ ] It’s better to delete commented code. If you need to review a previous version of your code, use git history.

https://github.com/Qoosim/the-next-web/blob/c042aa1c6c96691d9197875413cc96b90954f5a5/css/style.css#L1007-L1012

https://github.com/Qoosim/the-next-web/blob/c042aa1c6c96691d9197875413cc96b90954f5a5/css/style.css#L328-L336

- [ ] Properly set up linter for this project. ( _Refer to [this repo](https://github.com/microverseinc/linters-config/tree/master/css) and make sure you set it up correctly_ )

**Kindly submit another code review request after fixing those issues**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi @mihrab34 and @Qoosim,

**Amazing job thus far, guys!** :raised_hands:  Just one more thing to wrap this up:

- [ ] Setup linter properly. You can check [here](https://github.com/microverseinc/linters-config/tree/master/css) to see how to go about that. It should appear like the image below once you have fixed it.
linter2

Also, do not forget to close [this issue](https://github.com/Qoosim/the-next-web/issues/2).

**Kindly submit for another code review once this has been fixed.**

_Happy coding!_ :tada:

**Review by Forison — APPROVED** [review]
# Hi team 👋
Good Job on implementing the changes suggested by colleagues earlier.
#### Go ahead merge to master
## Project is approved 💪
#### Happy coding

**Pull request merged**
